baseURL = "https://t1elx.github.io/"
languageCode = "ru"
title = "T1elx blog"
theme = "terminal"
[pagination]
  pagerSize = 5

[params]
  # Цвета: orange, blue, red, green, pink
  themeColor = "blue"
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  extendedTemplate = false

[menu]
  [[menu.main]]
    name = "Writeups"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup.highlight]
  noClasses = false

