baseURL = "https://t1elx.pw/"
languageCode = "ru"
title = "t1elx / offensive notes"
theme = "terminal"

enableRobotsTXT = true
enableGitInfo = true

[pagination]
  pagerSize = 5

[params]
  themeColor = "blue"
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  defaultTheme = "dark"
  env = "production"

[menu]
  [[menu.main]]
    name = "Writeups"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup.highlight]
  noClasses = false
  lineNos = true
  lineNumbersInTable = true
  guessSyntax = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4

[frontmatter]
  lastmod = ["lastmod", ":git", "date"]

[languages]
  [languages.ru]
    languageName = "Russian"
    title = "t1elx"

    [languages.ru.params.logo]
      logoText = "t1elx"
      logoHomeLink = "/"  
